services:
  app-1:
    build:
      context: app-1
      additional_contexts:
        - module=module
    x-develop:
      watch:
      - action: rebuild
        path: .
      - action: rebuild
        path: ../module

  app-2:
    build:
      context: app-2
      additional_contexts:
        - module=module
    x-develop:
      watch:
      - action: rebuild
        path: .
      - action: rebuild
        path: ../module
